// Papéis e permissões do PreçoCerto. A autorização real é verificada no backend.
import { supabase } from "./supabase";
export { supabase };
export type AppRole="super_admin"|"admin"|"moderator"|"merchant_owner"|"merchant_staff"|"consumer";
export const roleLabels:Record<AppRole,string>={super_admin:"Superadministrador",admin:"Administrador",moderator:"Moderador",merchant_owner:"Responsável por estabelecimento",merchant_staff:"Equipe do estabelecimento",consumer:"Consumidor"};
export const adminRoles:AppRole[]=["super_admin","admin","moderator"];
export type SessionProfile={userId:string;email:string|null;name:string;roles:AppRole[];isAdmin:boolean};
let profileCache:{value:SessionProfile|null;at:number}|null=null;let profileRequest:Promise<SessionProfile|null>|null=null;const PROFILE_TTL=20_000;
export function invalidateSessionProfile(){profileCache=null;profileRequest=null;}
function announceAuthChange(){invalidateSessionProfile();if(typeof window!=="undefined")window.dispatchEvent(new Event("pc:auth-changed"));}
export async function loadSessionProfile(force=false):Promise<SessionProfile|null>{
 if(!supabase)return null;if(!force&&profileCache&&Date.now()-profileCache.at<PROFILE_TTL)return profileCache.value;if(!force&&profileRequest)return profileRequest;
 profileRequest=(async()=>{const{data:sessionData}=await supabase.auth.getSession();const user=sessionData.session?.user;if(!user){profileCache={value:null,at:Date.now()};return null;}let roles:AppRole[]=[];const[{data:roleRows,error:rolesError},{data:profile}]=await Promise.all([supabase.from("user_roles").select("role").eq("user_id",user.id),supabase.from("profiles").select("display_name").eq("id",user.id).maybeSingle()]);if(!rolesError&&roleRows)roles=roleRows.map(row=>row.role as AppRole);const profileName=profile?.display_name?String(profile.display_name).trim():"";const metadataName=typeof user.user_metadata?.name==="string"?user.user_metadata.name.trim():"";const name=profileName||metadataName||user.email?.split("@")[0]||"Consumidor";const effectiveRoles:AppRole[]=roles.length?roles:["consumer"];const value:SessionProfile={userId:user.id,email:user.email??null,name,roles:effectiveRoles,isAdmin:effectiveRoles.some(role=>adminRoles.includes(role))};profileCache={value,at:Date.now()};return value;})();
 try{return await profileRequest;}finally{profileRequest=null;}
}
export function defaultRouteForProfile(profile:SessionProfile|null,preferred?:"consumer"|"merchant"){if(!profile)return"/";if(profile.roles.includes("super_admin")||profile.roles.includes("admin")||profile.roles.includes("moderator"))return"/admin";if(profile.roles.some(role=>role==="merchant_owner"||role==="merchant_staff"))return"/painel-lojista";if(preferred==="merchant")return"/lojista";return"/";}
export async function hasRole(role:AppRole):Promise<boolean>{if(!supabase)return false;const p=await loadSessionProfile();if(p?.roles.includes(role))return true;const{data:sessionData}=await supabase.auth.getSession();const userId=sessionData.session?.user?.id;if(!userId)return false;const{data,error}=await supabase.rpc("has_role",{_user_id:userId,_role:role});return !error&&data===true;}
export async function signIn(email:string,password:string){if(!supabase)return{error:"Autenticação indisponível: banco não configurado."};const{data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLocaleLowerCase("pt-BR"),password});if(error||!data.user||!data.session){const text=(error?.message||"").toLocaleLowerCase("pt-BR");if(text.includes("invalid login")||text.includes("invalid credentials"))return{error:"Cadastro não encontrado ou senha incorreta. Confira os dados ou crie sua conta."};if(text.includes("email not confirmed"))return{error:"Seu cadastro existe, mas o e-mail ainda precisa ser confirmado."};return{error:error?.message||"Não foi possível validar este cadastro."};}announceAuthChange();const profile=await loadSessionProfile(true);return{error:null,profile};}
export async function signInMerchantWithCpf(cpf:string,pin:string){if(!supabase)return{error:"Autenticação indisponível: banco não configurado."};try{const{data,error}=await supabase.functions.invoke("merchant-cpf-login",{body:{cpf,pin}});if(error)return{error:error.message||"Erro de conexão com o servidor de autenticação."};if(!data||data.error)return{error:data?.error||"CPF ou PIN incorretos."};if(!data.access_token||!data.refresh_token)return{error:"Resposta de autenticação inválida."};const{error:sessionError}=await supabase.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});if(!sessionError)announceAuthChange();return{error:sessionError?.message??null};}catch{return{error:"Ocorreu um erro inesperado ao tentar fazer login."};}}
export async function signUp(email:string,password:string,name:string){if(!supabase)return{error:"Cadastro indisponível: banco não configurado."};const cleanName=name.trim();const{data,error}=await supabase.auth.signUp({email:email.trim().toLocaleLowerCase("pt-BR"),password,options:{data:{name:cleanName,full_name:cleanName}}});if(error)return{error:error.message};if(!data.user)return{error:"Não foi possível concluir o cadastro."};announceAuthChange();return{error:null};}
export async function requestPasswordReset(email:string){if(!supabase)return{error:"Recuperação indisponível: banco não configurado."};const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/redefinir-senha`});return{error:error?.message??null};}
export async function signOut(){if(supabase)await supabase.auth.signOut();announceAuthChange();}
export async function syncFavorites(productIds:string[]):Promise<void>{if(!supabase)return;const{data:{session}}=await supabase.auth.getSession();if(!session?.user)return;const userId=session.user.id;const{data:remoteFavs}=await supabase.from("user_favorites").select("product_id").eq("user_id",userId);const remoteIds=new Set(remoteFavs?.map(f=>f.product_id)||[]);const localIds=new Set(productIds);const toInsert=productIds.filter(id=>!remoteIds.has(id)).map(id=>({user_id:userId,product_id:id}));const toRemove=Array.from(remoteIds).filter(id=>!localIds.has(id));if(toInsert.length)await supabase.from("user_favorites").insert(toInsert);if(toRemove.length)await supabase.from("user_favorites").delete().in("product_id",toRemove).eq("user_id",userId);}
export async function loadRemoteFavorites():Promise<string[]>{if(!supabase)return[];const{data:{session}}=await supabase.auth.getSession();if(!session?.user)return[];const{data,error}=await supabase.from("user_favorites").select("product_id").eq("user_id",session.user.id);return error?[]:data.map(f=>f.product_id);}
