import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Activity, BadgeCheck, BarChart3, Bell, Building2, Check, CircleDollarSign, ClipboardCheck, Eye, LayoutDashboard, ListChecks, LogOut, PackageSearch, RefreshCw, Search, ShieldCheck, ShoppingBasket, Store, Tag, UsersRound, X } from 'lucide-react';
import { loadSessionProfile, signOut, type SessionProfile } from '../lib/roles';
import { cancelOrder, loadAdminSnapshot, reviewMerchantApplication, setUserRole, updateMerchant, type AdminSnapshot } from '../lib/adminPlatform';
import './AdminControlCenter.css';

const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const integer = new Intl.NumberFormat('pt-BR');
const dateTime = new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'});
const fmtDate=(v?:string|null)=>v?dateTime.format(new Date(v)):'—';
const roleLabel:Record<string,string>={super_admin:'Superadministrador',admin:'Administrador',moderator:'Moderador',merchant_owner:'Lojista',merchant_staff:'Equipe da loja',consumer:'Consumidor'};

type Section='overview'|'prices'|'merchants'|'orders'|'users'|'reputation'|'audit';
function sectionFromPath(path:string):Section { if(path.includes('/precos'))return'prices'; if(path.includes('/comerciantes'))return'merchants'; if(path.includes('/pedidos'))return'orders'; if(path.includes('/usuarios'))return'users'; if(path.includes('/reputacao'))return'reputation'; if(path.includes('/auditoria'))return'audit'; return'overview'; }

export function AdminControlCenter(){
  const location=useLocation(); const navigate=useNavigate();
  const section=sectionFromPath(location.pathname);
  const [profile,setProfile]=useState<SessionProfile|null>(null);
  const [authorized,setAuthorized]=useState<boolean|null>(null);
  const [data,setData]=useState<AdminSnapshot|null>(null);
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [query,setQuery]=useState('');
  const refresh=async()=>{setLoading(true);setError('');try{const p=await loadSessionProfile();setProfile(p);setAuthorized(Boolean(p?.isAdmin));if(!p?.isAdmin){setData(null);return;}setData(await loadAdminSnapshot());}catch(e:any){setError(e?.message||'Falha ao carregar o painel.');}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[]);
  const act=async(key:string,fn:()=>Promise<{error:string|null}>)=>{setBusy(key);setError('');const r=await fn();setBusy('');if(r.error){setError(r.error);return;}await refresh();};
  const logout=async()=>{await signOut();navigate('/login');};
  const q=query.trim().toLocaleLowerCase('pt-BR');
  const filter=(rows:any[], fields:string[])=>!q?rows:rows.filter(row=>fields.some(f=>String(row?.[f]??'').toLocaleLowerCase('pt-BR').includes(q)));
  if(authorized===null||loading&&!data)return <main className="acc-state"><RefreshCw className="spin"/><h1>Carregando administração…</h1></main>;
  if(!authorized)return <main className="acc-state"><ShieldCheck/><h1>Acesso administrativo restrito</h1><p>Entre com uma conta administrativa autorizada.</p><Link to="/login">Entrar</Link></main>;
  if(!data)return <main className="acc-state"><X/><h1>Não foi possível abrir o painel</h1><p>{error||'Tente novamente.'}</p><button onClick={()=>void refresh()}>Tentar novamente</button></main>;
  const s=data.summary||{};
  return <div className="acc-shell">
    <aside className="acc-sidebar"><Link to="/" className="acc-brand"><img src="/logo-preco-certo-inversa.svg" alt="PreçoCerto"/></Link><nav>
      <small>INTELIGÊNCIA</small><Nav to="/admin" active={section==='overview'} icon={<LayoutDashboard/>}>Visão geral</Nav><Nav to="/admin/precos" active={section==='prices'} icon={<BarChart3/>}>Mapa de preços</Nav>
      <small>OPERAÇÕES</small><Nav to="/admin/comerciantes" active={section==='merchants'} icon={<Building2/>}>Comerciantes <b>{s.pendingApplications||0}</b></Nav><Nav to="/admin/pedidos" active={section==='orders'} icon={<ShoppingBasket/>}>Pedidos</Nav>
      <small>USUÁRIOS</small><Nav to="/admin/usuarios" active={section==='users'} icon={<UsersRound/>}>Usuários</Nav><Nav to="/admin/reputacao" active={section==='reputation'} icon={<ListChecks/>}>Atividade</Nav>
      <small>SEGURANÇA</small><Nav to="/admin/auditoria" active={section==='audit'} icon={<ClipboardCheck/>}>Auditoria</Nav>
    </nav><footer><span><ShieldCheck/> {profile?.roles.includes('super_admin')?'Superadministrador':'Administrador'}</span><button onClick={logout}><LogOut/> Sair</button></footer></aside>
    <main className="acc-main"><header className="acc-top"><div><small>PAINEL EXECUTIVO</small><h1>{title(section)}</h1><p>{subtitle(section)}</p></div><div className="acc-top-actions"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nesta área"/></label><button onClick={()=>void refresh()} disabled={loading} aria-label="Atualizar"><RefreshCw className={loading?'spin':''}/></button><Link to="/">Ver site</Link></div></header>
    {error&&<div className="acc-error">{error}<button onClick={()=>setError('')}><X/></button></div>}
    {section==='overview'&&<Overview data={data}/>} {section==='prices'&&<Prices rows={filter(data.prices,['product_name','category','establishment_name','neighborhood'])} map={filter(data.priceMap,['name','neighborhood'])}/>} {section==='merchants'&&<Merchants applications={filter(data.applications,['business_name','owner_name','email','status'])} merchants={filter(data.merchants,['name','business_type','status','email'])} busy={busy} act={act}/>} {section==='orders'&&<Orders rows={filter(data.orders,['order_number','merchant_name','customer_name','status','payment_status'])} busy={busy} act={act}/>} {section==='users'&&<Users rows={filter(data.users,['display_name','email','profile_role'])} isSuper={Boolean(profile?.roles.includes('super_admin'))} busy={busy} act={act}/>} {section==='reputation'&&<ActivityView rows={filter(data.activity,['action','entity_type'])}/>} {section==='audit'&&<Audit rows={filter(data.audit,['action','entity_type','actor_name','actor_email','merchant_name'])}/>} </main>
  </div>;
}

function Nav({to,active,icon,children}:{to:string;active:boolean;icon:React.ReactNode;children:React.ReactNode}){return <Link to={to} className={active?'active':''}>{icon}<span>{children}</span></Link>}
function title(s:Section){return({overview:'Visão geral',prices:'Mapa e cobertura de preços',merchants:'Comerciantes e solicitações',orders:'Pedidos da plataforma',users:'Usuários e permissões',reputation:'Atividade e reputação',audit:'Auditoria administrativa'})[s]}
function subtitle(s:Section){return({overview:'Panorama operacional real do PreçoCerto.',prices:'Acompanhe preços coletados, variações e cobertura por estabelecimento.',merchants:'Aprove cadastros e controle a operação das lojas.',orders:'Acompanhe pedidos e intervenha quando necessário.',users:'Consulte contas e gerencie permissões com segurança.',reputation:'Entenda os eventos e sinais de uso da plataforma.',audit:'Rastreabilidade das ações administrativas e operacionais.'})[s]}

function Overview({data}:{data:AdminSnapshot}){const s=data.summary;const cards=[['Comerciantes ativos',s.activeMerchants,Store],['Solicitações pendentes',s.pendingApplications,Building2],['Pedidos hoje',s.ordersToday,ShoppingBasket],['Usuários',s.users,UsersRound],['Preços hoje',s.pricesToday,Tag],['GMV hoje',money.format(s.gmvToday||0),CircleDollarSign]] as const;return <><section className="acc-cards">{cards.map(([l,v,I])=><article key={l}><I/><span>{l}</span><strong>{typeof v==='number'?integer.format(v):v}</strong></article>)}</section><section className="acc-grid"><article className="acc-panel wide"><header><div><small>COBERTURA</small><h2>Operação da plataforma</h2></div><BadgeCheck/></header><div className="acc-kpis"><div><strong>{integer.format(s.prices||0)}</strong><span>preços registrados</span></div><div><strong>{integer.format(s.merchants||0)}</strong><span>comerciantes</span></div><div><strong>{integer.format(s.orders||0)}</strong><span>pedidos totais</span></div><div><strong>{money.format(s.platformRevenueToday||0)}</strong><span>receita hoje</span></div></div></article><article className="acc-panel"><header><div><small>ATENÇÃO</small><h2>Fila operacional</h2></div><Bell/></header><ul className="acc-list"><li><span>Cadastros aguardando análise</span><strong>{s.pendingApplications||0}</strong></li><li><span>Comerciantes ativos</span><strong>{s.activeMerchants||0}</strong></li><li><span>Pedidos de hoje</span><strong>{s.ordersToday||0}</strong></li></ul></article><article className="acc-panel"><header><div><small>ÚLTIMAS AÇÕES</small><h2>Auditoria recente</h2></div><Eye/></header><ul className="acc-list">{data.audit.slice(0,5).map((r:any)=><li key={r.id}><span>{r.action}<small>{r.actor_name||r.actor_email||'Sistema'}</small></span><em>{fmtDate(r.created_at)}</em></li>)}{!data.audit.length&&<li><span>Nenhuma ação registrada</span></li>}</ul></article></section></>}

function Prices({rows,map}:{rows:any[];map:any[]}){return <><section className="acc-grid"><article className="acc-panel wide"><header><div><small>COBERTURA LOCAL</small><h2>Estabelecimentos com mais preços</h2></div><BarChart3/></header><div className="acc-bars">{map.slice(0,12).map((r:any)=>{const max=Math.max(...map.map((x:any)=>Number(x.price_count)||0),1);return <div key={r.id}><span><strong>{r.name}</strong><small>{r.neighborhood||'Feijó'}</small></span><i><b style={{width:`${Math.max(5,(Number(r.price_count)/max)*100)}%`}}/></i><em>{r.price_count}</em></div>})}</div></article></section><Table heads={['Produto','Estabelecimento','Valor','Variação','Atualizado']} rows={rows.map((r:any)=><tr key={r.id}><td><strong>{r.product_name}</strong><small>{r.category}</small></td><td>{r.establishment_name}<small>{r.neighborhood}</small></td><td><b>{money.format(Number(r.value)||0)}</b></td><td className={Number(r.variation_percent)>0?'bad':Number(r.variation_percent)<0?'good':''}>{r.variation_percent==null?'—':`${Number(r.variation_percent)>0?'+':''}${r.variation_percent}%`}</td><td>{fmtDate(r.captured_at)}</td></tr>)}/></>}

function Merchants({applications,merchants,busy,act}:{applications:any[];merchants:any[];busy:string;act:any}){const pending=applications.filter(a=>a.status==='pending');return <><section className="acc-panel"><header><div><small>ONBOARDING</small><h2>Solicitações pendentes</h2></div><strong>{pending.length}</strong></header><div className="acc-application-grid">{pending.map(a=><article key={a.id}><div><small>{a.business_type||a.kind||'comércio local'}</small><h3>{a.business_name}</h3><p>{a.owner_name} · {a.email}</p><span>{a.neighborhood||'Feijó'} · {fmtDate(a.created_at)}</span></div><div><button disabled={!!busy} onClick={()=>void act(`approve-${a.id}`,()=>reviewMerchantApplication(a.id,'approved','Aprovado pelo painel administrativo'))}><Check/> Aprovar</button><button className="danger" disabled={!!busy} onClick={()=>{const reason=prompt('Motivo da rejeição:')||'';if(reason)void act(`reject-${a.id}`,()=>reviewMerchantApplication(a.id,'rejected',reason));}}><X/> Rejeitar</button></div></article>)}{!pending.length&&<p className="acc-empty">Nenhuma solicitação aguardando análise.</p>}</div></section><Table heads={['Comerciante','Status','Catálogo','Pedidos','Vendas online','Ações']} rows={merchants.map(m=><tr key={m.id}><td><strong>{m.name}</strong><small>{m.business_type||'comércio local'}</small></td><td><Status value={m.status}/></td><td>{m.product_count}</td><td>{m.order_count}</td><td>{m.online_sales_enabled?'Ativas':'Desativadas'}</td><td className="actions"><button disabled={!!busy} onClick={()=>void act(`status-${m.id}`,()=>updateMerchant(m.id,{status:m.status==='active'?'suspended':'active'}))}>{m.status==='active'?'Suspender':'Ativar'}</button><button disabled={!!busy} onClick={()=>void act(`sales-${m.id}`,()=>updateMerchant(m.id,{onlineSalesEnabled:!m.online_sales_enabled}))}>{m.online_sales_enabled?'Desativar vendas':'Ativar vendas'}</button></td></tr>)}/></>}

function Orders({rows,busy,act}:{rows:any[];busy:string;act:any}){return <Table heads={['Pedido','Comerciante','Cliente','Status','Pagamento','Total','Criado','Ação']} rows={rows.map(o=><tr key={o.id}><td><strong>{o.order_number}</strong></td><td>{o.merchant_name}</td><td>{o.customer_name}</td><td><Status value={o.status}/></td><td>{o.payment_status}</td><td><b>{money.format(Number(o.total)||0)}</b></td><td>{fmtDate(o.created_at)}</td><td className="actions">{!['cancelled','delivered'].includes(o.status)&&<button className="danger" disabled={!!busy} onClick={()=>{const reason=prompt('Motivo do cancelamento:','Intervenção administrativa')||'';if(reason)void act(`cancel-${o.id}`,()=>cancelOrder(o.id,reason));}}>Cancelar</button>}</td></tr>)}/>}

function Users({rows,isSuper,busy,act}:{rows:any[];isSuper:boolean;busy:string;act:any}){return <Table heads={['Usuário','Perfil','Papéis','Cadastro','Último acesso','Permissões']} rows={rows.map(u=>{const roles=Array.isArray(u.roles)?u.roles:[];const admin=roles.includes('admin');const moderator=roles.includes('moderator');return <tr key={u.id}><td><strong>{u.display_name||'Usuário'}</strong><small>{u.email||'sem e-mail'}</small></td><td>{u.profile_role}</td><td>{roles.map((r:string)=><span className="acc-chip" key={r}>{roleLabel[r]||r}</span>)}</td><td>{fmtDate(u.created_at)}</td><td>{fmtDate(u.last_sign_in_at)}</td><td className="actions">{isSuper&&<><button disabled={!!busy} onClick={()=>void act(`admin-${u.id}`,()=>setUserRole(u.id,'admin',!admin))}>{admin?'Remover admin':'Tornar admin'}</button><button disabled={!!busy} onClick={()=>void act(`mod-${u.id}`,()=>setUserRole(u.id,'moderator',!moderator))}>{moderator?'Remover moderador':'Moderador'}</button></>}</td></tr>})}/>}

function ActivityView({rows}:{rows:any[]}){return <section className="acc-grid"><article className="acc-panel wide"><header><div><small>SINAIS DE USO</small><h2>Atividade por tipo</h2></div><Activity/></header><div className="acc-activity">{rows.map((r:any,i)=><article key={`${r.action}-${r.entity_type}-${i}`}><span><strong>{r.action}</strong><small>{r.entity_type||'evento'}</small></span><b>{r.events}</b><em>{fmtDate(r.last_event)}</em></article>)}{!rows.length&&<p className="acc-empty">Ainda não há eventos de atividade suficientes.</p>}</div></article></section>}
function Audit({rows}:{rows:any[]}){return <Table heads={['Ação','Entidade','Responsável','Comerciante','Data']} rows={rows.map(r=><tr key={r.id}><td><strong>{r.action}</strong></td><td>{r.entity_type}<small>{r.entity_id}</small></td><td>{r.actor_name||r.actor_email||'Sistema'}</td><td>{r.merchant_name||'—'}</td><td>{fmtDate(r.created_at)}</td></tr>)}/>}
function Status({value}:{value:string}){return <span className={`acc-status s-${String(value).replace(/_/g,'-')}`}>{value}</span>}
function Table({heads,rows}:{heads:string[];rows:React.ReactNode[]}){return <section className="acc-table-wrap"><div className="acc-table-scroll"><table className="acc-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={heads.length} className="acc-empty">Nenhum registro encontrado.</td></tr>}</tbody></table></div></section>}
