import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BadgeCheck, BookOpen, BriefcaseBusiness, Croissant, Grid2X2, MapPin, PackageSearch, Pill, Search, ShoppingBasket, Store, type LucideIcon } from "lucide-react";
import { Link } from "react-router-dom";
import type { CatalogPayload, Product, StoreRow } from "../data/catalog";
import { fetchSectorCatalog, prefetchSectorCatalog, productHasSectorOffer, sectorProducts, sectorStores } from "../data/sectorCatalog";
import "./MarketplaceSectors.css";
import "./ExploreLayoutFix.css";
import "./SectorContentArchitecture.css";

export type MarketplaceSectorId = "all" | "markets" | "pharmacies" | "bakery" | "books" | "services";
export type MarketplaceSector = {id:MarketplaceSectorId;label:string;shortLabel:string;eyebrow:string;title:string;description:string;searchHint:string;href:string;icon:LucideIcon;productCategories:string[];businessKinds:string[];highlights:string[];examples:string[]};
export const marketplaceSectors:MarketplaceSector[]=[
 {id:"markets",label:"Mercados, mercearias e açougues",shortLabel:"Mercados",eyebrow:"Compras do dia a dia",title:"Compras locais organizadas pelo estabelecimento certo.",description:"Compare alimentos, bebidas, limpeza e outros itens somente quando houver preço realmente cadastrado em um comércio compatível.",searchHint:"Arroz, café, limpeza ou mercado…",href:"/mercados",icon:ShoppingBasket,productCategories:["mercearia","laticinios","limpeza","hortifruti","bebidas","higiene","congelados"],businessKinds:["market","grocery","supermarket","beverage"],highlights:["Catálogos reais","Preços vinculados à loja","Comparação local"],examples:["Mercados","Mercearias","Bebidas","Hortifruti"]},
 {id:"pharmacies",label:"Farmácias e saúde",shortLabel:"Farmácias",eyebrow:"Saúde e cuidados",title:"Farmácias aparecem quando há catálogo farmacêutico real.",description:"Medicamentos, higiene e cuidados pessoais só entram aqui quando estiverem vinculados a uma farmácia ou estabelecimento de saúde cadastrado.",searchHint:"Farmácia, higiene ou produto de saúde…",href:"/farmacias",icon:Pill,productCategories:["farmacia","medicamentos","saude","higiene","perfumaria","cuidados pessoais"],businessKinds:["pharmacy","health"],highlights:["Sem associações artificiais","Catálogo por farmácia","Dados verificáveis"],examples:["Farmácias","Higiene","Perfumaria","Cuidados pessoais"]},
 {id:"bakery",label:"Padarias e alimentação",shortLabel:"Alimentação",eyebrow:"Comida perto de você",title:"Alimentação local sem misturar com supermercado.",description:"Padarias, lanchonetes, restaurantes e produtos preparados aparecem apenas quando o estabelecimento e o catálogo pertencem a este setor.",searchHint:"Pão, bolo, lanche ou padaria…",href:"/padarias",icon:Croissant,productCategories:["padaria","alimentos preparados","lanches","refeicoes","doces","salgados"],businessKinds:["bakery","restaurant","pizzeria","snack_bar","food"],highlights:["Cardápios separados","Negócios compatíveis","Consulta direta"],examples:["Padarias","Lanchonetes","Restaurantes","Doces e salgados"]},
 {id:"books",label:"Livros, autores e cultura",shortLabel:"Livros e cultura",eyebrow:"Cultura e conhecimento",title:"Autores, obras e projetos em uma experiência editorial própria.",description:"Perfis culturais não são tratados como supermercados. Aqui o foco é contexto, autoria, obras e projetos locais.",searchHint:"Título, autora, autor ou projeto cultural…",href:"/livros",icon:BookOpen,productCategories:["livros","literatura","cultura","educacao"],businessKinds:["books_author","bookstore","publisher","culture","culture_music"],highlights:["Perfis editoriais","Obras e autores","Projetos culturais"],examples:["Autores","Livros","Editoras","Projetos culturais"]},
 {id:"services",label:"Serviços e profissionais",shortLabel:"Serviços",eyebrow:"Profissionais locais",title:"Serviços organizados pela especialidade real do prestador.",description:"Autônomos e prestadores aparecem como perfis de serviço, com área atendida e informações úteis — sem produtos fictícios.",searchHint:"Serviço, profissão ou especialidade…",href:"/servicos",icon:BriefcaseBusiness,productCategories:["servicos","profissionais","autonomos"],businessKinds:["services","professional","freelancer"],highlights:["Perfis profissionais","Área atendida","Contato objetivo"],examples:["Autônomos","Profissionais","Serviços locais"]},
];
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR").trim();
export function getMarketplaceSector(value:string|null|undefined){return marketplaceSectors.find(s=>s.id===value)||null}
export function inferProductSector(category:string):MarketplaceSectorId{const n=normalize(category);return marketplaceSectors.find(s=>s.productCategories.some(i=>n.includes(normalize(i))))?.id||"markets"}
export function SectorNavigator({active="all",compact=false,counts}:{active?:MarketplaceSectorId;compact?:boolean;counts?:Partial<Record<MarketplaceSectorId,number>>}){const warm=()=>prefetchSectorCatalog();return <nav className={`sector-nav${compact?" sector-nav--compact":""}`} aria-label="Explorar por setor"><Link className={active==="all"?"is-active":""} to="/explorar"><Grid2X2/><span><strong>Todos os setores</strong><small>Visão geral da cidade</small></span></Link>{marketplaceSectors.map(s=><Link key={s.id} className={active===s.id?"is-active":""} to={s.href} onPointerEnter={warm} onFocus={warm}><s.icon/><span><strong>{s.shortLabel}</strong><small>{counts?.[s.id]!==undefined?`${counts[s.id]} opções reais`:s.examples.slice(0,2).join(" · ")}</small></span></Link>)}</nav>}
function Header(){return <header className="sector-header"><div className="sector-shell"><Link className="sector-brand" to="/"><img src="/logo-preco-certo-inversa.svg" alt="PreçoCerto"/></Link><nav><Link to="/buscar">Buscar <Search/></Link><Link to="/explorar">Todos os setores <Grid2X2/></Link></nav></div></header>}
function Footer(){return <footer className="sector-footer"><div className="sector-shell"><Link className="sector-brand" to="/"><img src="/logo-preco-certo-inversa.svg" alt="PreçoCerto"/></Link><span>Setores organizados por dados realmente cadastrados.</span><Link to="/estabelecimentos">Ver estabelecimentos <ArrowRight/></Link></div></footer>}
function CulturalProfiles(){return <div className="sector-profile-grid"><Link to="/dorinha-barroso"><BookOpen/><span><small>AUTORA</small><strong>Dorinha Barroso</strong><p>Perfil editorial dedicado para conhecer a autora e seus conteúdos culturais.</p></span><ArrowRight/></Link><Link to="/fremix-producoes"><Store/><span><small>PROJETO CULTURAL</small><strong>Fremix Produções</strong><p>Espaço próprio para iniciativas e conteúdos culturais locais.</p></span><ArrowRight/></Link></div>}
function RealSectorContent({catalog,sector}:{catalog:CatalogPayload|null;sector:MarketplaceSector}){if(sector.id==="books")return <section className="sector-real-content"><header><div><span>CONTEÚDO CULTURAL</span><h2>Perfis com contexto próprio</h2><p>Pessoas e projetos culturais são apresentados como perfis editoriais, sem associação artificial com produtos.</p></div></header><CulturalProfiles/></section>;if(!catalog)return <section className="sector-real-content"><div className="sector-empty-real"><span className="sector-loading-dot"/><span><strong>Carregando dados do setor</strong><small>Confirmando catálogos e estabelecimentos vinculados.</small></span></div></section>;const matches=sectorStores(catalog,sector);if(!matches.length)return <section className="sector-real-content"><header><div><span>CATÁLOGO REAL</span><h2>Ainda não há catálogo ativo neste setor</h2><p>Não exibimos produtos ou lojas apenas por categoria. Esta área será preenchida quando houver cadastro e preço vinculados a um estabelecimento compatível.</p></div></header><div className="sector-empty-real"><PackageSearch/><span><strong>Nenhuma associação artificial</strong><small>Os dados aparecem automaticamente quando o catálogo real existir.</small></span></div></section>;return <section className="sector-real-content"><header><div><span>CATÁLOGO REAL</span><h2>Opções locais confirmadas</h2><p>Somente negócios com produtos realmente vinculados a este setor aparecem abaixo.</p></div><Link to={`/estabelecimentos?setor=${sector.id}`}>Ver diretório <ArrowRight/></Link></header><div className="sector-store-grid">{matches.slice(0,8).map(({store,count})=><Link to={`/estabelecimento/${store.slug||store.id}`} key={store.id} className="sector-store-card"><i style={{background:store.color}}><Store/></i><span><small>{store.neighborhood||"Feijó"}</small><strong>{store.name}</strong><em>{count} {count===1?"item vinculado":"itens vinculados"}</em></span><b>ABRIR CATÁLOGO</b><ArrowRight/></Link>)}</div></section>}
export function MarketplaceSectorLanding({sector}:{sector:MarketplaceSector}){const Icon=sector.icon;const[catalog,setCatalog]=useState<CatalogPayload|null>(null);useEffect(()=>{let active=true;void fetchSectorCatalog().then(data=>{if(active)setCatalog(data)}).catch(()=>undefined);return()=>{active=false}},[]);const productCount=catalog?sectorProducts(catalog,sector).length:0;const storeCount=catalog?sectorStores(catalog,sector).length:0;return <div className={`sector-page sector-page--${sector.id}`}><Header/><main id="conteudo-principal" className="sector-main"><section className="sector-hero"><div className="sector-shell sector-hero__grid"><div className="sector-hero__copy"><span className="sector-eyebrow"><Icon/>{sector.eyebrow}</span><h1>{sector.title}</h1><p>{sector.description}</p><div className="sector-example-chips">{sector.examples.map(example=><span key={example}>{example}</span>)}</div><div className="sector-hero__actions"><Link to={`/buscar?setor=${sector.id}`}><Search/>Pesquisar neste setor</Link><a href="#conteudo-local"><Store/>Ver opções reais</a></div></div><aside><span>SETOR VERIFICADO</span><Icon/><strong>{sector.label}</strong><div className="sector-hero__metrics"><b>{storeCount}</b><small>estabelecimentos com vínculo</small><b>{productCount}</b><small>itens compatíveis</small></div><p>Contagens baseadas no catálogo realmente cadastrado.</p></aside></div></section><section className="sector-content sector-shell"><div className="sector-highlights">{sector.highlights.map((h,i)=><div key={h}><span>0{i+1}</span><BadgeCheck/><strong>{h}</strong></div>)}</div><div id="conteudo-local"><RealSectorContent catalog={catalog} sector={sector}/></div><div className="sector-content__heading sector-content__heading--secondary"><div><span>CONTINUE EXPLORANDO</span><h2>Troque de setor sem perder o contexto.</h2></div><p>Cada área tem regras próprias para evitar misturar produtos, lojas e perfis incompatíveis.</p></div><SectorNavigator active={sector.id} compact/></section></main><Footer/></div>}
export function MarketplaceExplorePage(){const[catalog,setCatalog]=useState<CatalogPayload|null>(null);useEffect(()=>{let active=true;void fetchSectorCatalog().then(data=>{if(active)setCatalog(data)}).catch(()=>undefined);return()=>{active=false}},[]);const counts=useMemo(()=>catalog?Object.fromEntries(marketplaceSectors.map(sector=>[sector.id,sectorStores(catalog,sector).length])) as Partial<Record<MarketplaceSectorId,number>>:{},[catalog]);return <div className="sector-page sector-page--all"><Header/><main className="sector-main"><section className="sector-hero sector-hero--explore"><div className="sector-shell sector-hero__grid"><div className="sector-hero__copy"><span className="sector-eyebrow"><Grid2X2/>PREÇOCERTO POR SETOR</span><h1>Escolha o que procura. A plataforma separa o que realmente pertence ali.</h1><p>Produtos só aparecem quando há vínculo real com estabelecimentos compatíveis. Cultura e serviços têm experiências próprias.</p><Link className="sector-primary-link" to="/estabelecimentos">Ver estabelecimentos <ArrowRight/></Link></div><aside><MapPin/><strong>Feijó, Acre</strong><p>Catálogo organizado por vínculo real, não por suposição.</p></aside></div></section><section className="sector-content sector-shell"><SectorNavigator compact counts={counts}/></section></main><Footer/></div>}
