import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { ArrowLeft, BadgeCheck, Building2, CheckCircle2, LoaderCircle, Minus, PackagePlus, PiggyBank, Plus, Save, Search, ShoppingBasket, Sparkles, Store, Trash2, WalletCards } from "lucide-react";
import { fetchCatalog } from "../data/remoteCatalog";
import type { Product, ProductOffer } from "../data/catalog";
import { loadSessionProfile, supabase, type SessionProfile } from "../lib/roles";
import "./SmartBasketPage.css";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
type Essential={key:string;label:string;keywords:string[];priority:number;quantity:(people:number)=>number};
type DesiredRow={label:string;product:Product;quantity:number;priority:number};
type PlannedItem={product:Product;quantity:number;offer:ProductOffer;subtotal:number;essential:string};
type Plan={strategy:"multi_store"|"single_store";total:number;items:PlannedItem[];stores:string[];missing:string[];savings:number;label:string;storeName?:string};
const ESSENTIALS:Essential[]=[
{key:"arroz",label:"Arroz",keywords:["arroz"],priority:1,quantity:p=>Math.max(1,Math.ceil(p/3))},{key:"feijao",label:"Feijão",keywords:["feijao"],priority:2,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"oleo",label:"Óleo",keywords:["oleo de soja","oleo"],priority:3,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"macarrao",label:"Macarrão",keywords:["macarrao"],priority:4,quantity:p=>Math.max(1,Math.ceil(p*1.5))},{key:"leite",label:"Leite",keywords:["leite integral","leite"],priority:5,quantity:p=>Math.max(1,p*2)},{key:"acucar",label:"Açúcar",keywords:["acucar"],priority:6,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"cafe",label:"Café",keywords:["cafe"],priority:7,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"farinha",label:"Farinha",keywords:["farinha de trigo","farinha"],priority:8,quantity:()=>1},{key:"sal",label:"Sal",keywords:["sal refinado","sal"],priority:9,quantity:()=>1},{key:"proteina",label:"Proteína",keywords:["frango","carne bovina","carne"],priority:10,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"ovos",label:"Ovos",keywords:["ovos","ovo"],priority:11,quantity:p=>Math.max(1,Math.ceil(p/3))},{key:"detergente",label:"Detergente",keywords:["detergente"],priority:12,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"sabao",label:"Sabão",keywords:["sabao em po","sabao"],priority:13,quantity:()=>1},{key:"papel",label:"Papel higiênico",keywords:["papel higienico"],priority:14,quantity:()=>1}];
function candidateFor(products:Product[],essential:Essential){return products.filter(product=>{const text=normalize(`${product.name} ${product.category} ${product.brand}`);return essential.keywords.some(k=>text.includes(normalize(k)))&&product.minPrice>0;}).sort((a,b)=>a.minPrice-b.minPrice||a.name.localeCompare(b.name,"pt-BR"))[0]||null;}
function cheapestOffer(product:Product):ProductOffer|null{return product.offers?.filter(o=>o.value>0).sort((a,b)=>a.value-b.value)[0]||(product.minPrice>0?{establishmentId:product.establishmentId,establishmentSlug:product.establishmentSlug,establishment:product.establishment,neighborhood:product.neighborhood,storeColor:product.storeColor,value:product.minPrice,capturedAt:product.capturedAt}:null);}
function suggestedRows(products:Product[],people:number):DesiredRow[]{return ESSENTIALS.map(e=>{const product=candidateFor(products,e);return product?{label:e.label,product,quantity:e.quantity(people),priority:e.priority}:null;}).filter(Boolean) as DesiredRow[];}
function buildMulti(rows:DesiredRow[],budget:number):Plan{const items:PlannedItem[]=[];const missing:string[]=[];let total=0;for(const row of rows){const offer=cheapestOffer(row.product);if(!offer){missing.push(row.label);continue;}let added=0;for(let i=0;i<row.quantity;i++){if(total+offer.value>budget)break;total+=offer.value;added++;}if(added)items.push({product:row.product,quantity:added,offer,subtotal:offer.value*added,essential:row.label});else missing.push(row.label);}return{strategy:"multi_store",total,items,stores:[...new Set(items.map(i=>i.offer.establishment))],missing,savings:0,label:"Menor preço em várias lojas"};}
function buildSingle(rows:DesiredRow[],budget:number):Plan{const stores=new Set<string>();rows.forEach(r=>r.product.offers?.forEach(o=>stores.add(o.establishment)));let best:Plan|null=null;let bestScore=-1;for(const storeName of stores){const items:PlannedItem[]=[];const missing:string[]=[];let total=0;let score=0;for(const row of rows){const offer=row.product.offers?.find(o=>o.establishment===storeName);if(!offer){missing.push(row.label);continue;}let added=0;for(let i=0;i<row.quantity;i++){if(total+offer.value>budget)break;total+=offer.value;added++;}if(added){items.push({product:row.product,quantity:added,offer,subtotal:offer.value*added,essential:row.label});score+=(110-row.priority)*1000+added;}else missing.push(row.label);}if(!best||score>bestScore||(score===bestScore&&total<best.total)){bestScore=score;best={strategy:"single_store",total,items,stores:items.length?[storeName]:[],missing,savings:0,label:"Melhor cesta em uma loja",storeName};}}return best||{strategy:"single_store",total:0,items:[],stores:[],missing:rows.map(r=>r.label),savings:0,label:"Melhor cesta em uma loja"};}
function readStoredPrefill(){try{const raw=sessionStorage.getItem("precocerto:smart-basket-prefill");return raw?JSON.parse(raw) as {budget?:number;people?:number}:{};}catch{return{};}}
export function SmartBasketPage(){
const navigate=useNavigate();const[searchParams]=useSearchParams();const stored=useMemo(readStoredPrefill,[]);const initialBudget=Math.max(50,Number(searchParams.get("budget")||stored.budget||350));const initialPeople=Math.min(8,Math.max(1,Number(searchParams.get("people")||stored.people||2)));
const[profile,setProfile]=useState<SessionProfile|null>(null),[authLoading,setAuthLoading]=useState(true),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true);const[budget,setBudget]=useState(initialBudget),[income,setIncome]=useState<number|"">(""),[people,setPeople]=useState(initialPeople),[selected,setSelected]=useState<"multi_store"|"single_store">("multi_store"),[saving,setSaving]=useState(false),[message,setMessage]=useState("");const[selectionMode,setSelectionMode]=useState<"smart"|"custom">("smart"),[query,setQuery]=useState(""),[custom,setCustom]=useState<Record<string,number>>({});
useEffect(()=>{loadSessionProfile().then(p=>{setProfile(p);setAuthLoading(false);if(!p)navigate(`/login?redirect=${encodeURIComponent(`/cesta-inteligente?budget=${budget}&people=${people}`)}`,{replace:true});});},[navigate,budget,people]);
useEffect(()=>{fetchCatalog().then(c=>setProducts(c.products)).finally(()=>setLoading(false));},[]);useEffect(()=>{sessionStorage.setItem("precocerto:smart-basket-prefill",JSON.stringify({budget,people}));},[budget,people]);
const suggestedBudget=useMemo(()=>income?Math.max(50,Math.round(Number(income)*.25)):null,[income]);
const customRows=useMemo(()=>Object.entries(custom).map(([id,quantity],index)=>{const product=products.find(p=>p.id===id);return product?{label:product.name,product,quantity,priority:index+1}:null;}).filter(Boolean) as DesiredRow[],[custom,products]);const rows=useMemo(()=>selectionMode==="custom"?customRows:suggestedRows(products,people),[selectionMode,customRows,products,people]);
const searchResults=useMemo(()=>{const q=normalize(query);if(q.length<2)return[];return products.filter(p=>p.minPrice>0&&normalize(`${p.name} ${p.brand} ${p.category}`).includes(q)&&!custom[p.id]).sort((a,b)=>a.minPrice-b.minPrice).slice(0,8);},[query,products,custom]);
const multi=useMemo(()=>buildMulti(rows,Math.max(0,budget)),[rows,budget]),single=useMemo(()=>buildSingle(rows,Math.max(0,budget)),[rows,budget]);const baseline=Math.max(multi.total,single.total);multi.savings=Math.max(0,baseline-multi.total);single.savings=Math.max(0,baseline-single.total);const active=selected==="multi_store"?multi:single;
function addProduct(product:Product){setSelectionMode("custom");setCustom(current=>({...current,[product.id]:current[product.id]||1}));setQuery("");}function changeQty(id:string,delta:number){setCustom(current=>{const next=Math.max(0,(current[id]||1)+delta);const copy={...current};if(!next)delete copy[id];else copy[id]=next;return copy;});}
async function savePlan(){if(!profile||!supabase||!active.items.length)return;setSaving(true);setMessage("");const payload={user_id:profile.userId,name:`Cesta ${new Date().toLocaleDateString("pt-BR")}`,budget,household_income:income||null,household_size:people,strategy:active.strategy,total:active.total,savings:active.savings,store_count:active.stores.length,items:active.items.map(i=>({product_id:i.product.id,name:i.product.name,quantity:i.quantity,unit_price:i.offer.value,subtotal:i.subtotal,establishment:i.offer.establishment,establishment_id:i.offer.establishmentId}))};const{error}=await supabase.from("smart_basket_plans").insert(payload);setSaving(false);setMessage(error?`Não foi possível salvar: ${error.message}`:"Cesta salva na sua conta.");}
if(authLoading||loading)return <main className="smart-basket-state"><LoaderCircle className="spin"/><strong>Preparando sua cesta inteligente…</strong></main>;if(!profile)return null;
return <div className="smart-basket-page"><header className="smart-basket-top"><Link to="/cesta-basica"><ArrowLeft/> Minha lista</Link><div><Sparkles/><span><strong>Cesta Inteligente</strong><small>PreçoCerto · Feijó, AC</small></span></div><span className="smart-user"><BadgeCheck/>{profile.name}</span></header><main id="conteudo-principal" className="smart-basket-shell">
<section className="smart-basket-hero"><div><small>PLANEJAMENTO DE COMPRA</small><h1>Monte a melhor cesta para o dinheiro que você tem.</h1><p>Use nossa sugestão de itens essenciais ou escolha exatamente os produtos que deseja comprar.</p></div><ShoppingBasket/></section>
<section className="smart-planner"><div className="smart-controls"><label><span><WalletCards/> Quanto você tem disponível?</span><div className="money-input"><b>R$</b><input type="number" min="10" step="10" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)))}/></div></label><label><span>Renda mensal da família <em>opcional</em></span><div className="money-input"><b>R$</b><input type="number" min="0" step="100" value={income} placeholder="Ex.: 2.500" onChange={e=>setIncome(e.target.value===""?"":Number(e.target.value))}/></div>{suggestedBudget&&<button type="button" className="budget-suggestion" onClick={()=>setBudget(suggestedBudget)}>Usar referência de {brl.format(suggestedBudget)} <small>25% da renda · ajustável</small></button>}</label><label><span>Pessoas na casa</span><select value={people} onChange={e=>setPeople(Number(e.target.value))}>{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></label></div></section>
<section className="smart-product-picker"><header><div><small>PRODUTOS DA CESTA</small><h2>Como você quer montar sua lista?</h2></div><div className="smart-picker-tabs"><button className={selectionMode==="smart"?"is-active":""} onClick={()=>setSelectionMode("smart")}><Sparkles/> Sugestão inteligente</button><button className={selectionMode==="custom"?"is-active":""} onClick={()=>setSelectionMode("custom")}><PackagePlus/> Escolher meus produtos</button></div></header>{selectionMode==="custom"&&<><div className="smart-product-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque arroz, café, leite, frango, marca..."/></div>{searchResults.length>0&&<div className="smart-product-results">{searchResults.map(product=><button key={product.id} onClick={()=>addProduct(product)}><span><strong>{product.name}</strong><small>{product.brand||product.category} · a partir de {brl.format(product.minPrice)}</small></span><Plus/></button>)}</div>}<div className="smart-custom-list">{customRows.length?customRows.map(row=><article key={row.product.id}><div><strong>{row.product.name}</strong><small>{row.product.brand||row.product.category} · menor preço {brl.format(row.product.minPrice)}</small></div><div className="smart-qty"><button onClick={()=>changeQty(row.product.id,-1)} aria-label="Diminuir quantidade"><Minus/></button><b>{row.quantity}</b><button onClick={()=>changeQty(row.product.id,1)} aria-label="Aumentar quantidade"><Plus/></button></div><button className="smart-remove" onClick={()=>setCustom(current=>{const copy={...current};delete copy[row.product.id];return copy;})} aria-label={`Remover ${row.product.name}`}><Trash2/></button></article>):<div className="smart-custom-empty"><PackagePlus/><strong>Sua seleção está vazia.</strong><span>Pesquise acima e adicione os produtos que deseja comprar.</span></div>}</div></>}</section>
<section className="smart-results"><header><div><small>COMPARAÇÃO AUTOMÁTICA</small><h2>Escolha como quer comprar</h2></div><strong>Orçamento: {brl.format(budget)}</strong></header><div className="smart-strategies"><button type="button" className={selected==="multi_store"?"is-active":""} onClick={()=>setSelected("multi_store")}><span className="strategy-icon"><PiggyBank/></span><span><small>MAIOR ECONOMIA</small><strong>Menores preços em várias lojas</strong><em>O sistema escolhe a oferta mais barata de cada produto.</em></span><b>{brl.format(multi.total)}</b><i>{multi.stores.length} {multi.stores.length===1?"loja":"lojas"}</i></button><button type="button" className={selected==="single_store"?"is-active":""} onClick={()=>setSelected("single_store")}><span className="strategy-icon"><Store/></span><span><small>MAIS PRATICIDADE</small><strong>Melhor compra em uma loja</strong><em>{single.storeName?`Melhor combinação em ${single.storeName}.`:"Procura uma loja com a melhor combinação."}</em></span><b>{brl.format(single.total)}</b><i>{single.items.length} produtos atendidos</i></button></div></section>
<section className="smart-plan"><div className="smart-plan-list"><header><span><CheckCircle2/><div><small>CESTA CALCULADA</small><h2>{active.label}</h2></div></span><strong>{active.items.reduce((s,i)=>s+i.quantity,0)} unidades</strong></header>{active.items.map(item=><article key={`${item.product.id}-${item.offer.establishment}`}><div><small>{item.essential}</small><strong>{item.product.name}</strong><em>{item.product.size} · {item.offer.establishment}</em></div><span>{item.quantity} × {brl.format(item.offer.value)}</span><b>{brl.format(item.subtotal)}</b></article>)}{!active.items.length&&<div className="smart-empty">{selectionMode==="custom"&&!customRows.length?"Escolha ao menos um produto para calcular sua cesta.":"Nenhum item cabe neste orçamento com os preços disponíveis."}</div>}</div><aside className="smart-summary"><small>RESUMO</small><h2>{brl.format(active.total)}</h2><div><span>Saldo do orçamento</span><strong>{brl.format(Math.max(0,budget-active.total))}</strong></div><div><span>Estabelecimentos</span><strong>{active.stores.length}</strong></div><div><span>Produtos não atendidos</span><strong>{active.missing.length}</strong></div><button type="button" disabled={saving||!active.items.length} onClick={savePlan}>{saving?<LoaderCircle className="spin"/>:<Save/>}{saving?"Salvando…":"Salvar esta cesta"}</button>{message&&<p className={message.startsWith("Cesta salva")?"success":"error"}>{message}</p>}<Link to="/buscar"><Building2/> Explorar catálogo</Link></aside></section>
</main></div>;
}
