import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { ArrowRight, BookOpen, CheckCircle2, CreditCard, ExternalLink, Feather, MapPin, MessageCircle, Moon, QrCode, Share2, Sparkles, Store, Sun } from "lucide-react";
import { supabase } from "../lib/supabase";
import imagimacaoAsset from "../assets/uma-viagem-ao-mundo-da-imaginacao.png.asset.json";
import mentePerversaAsset from "../assets/mente-perversa.png.asset.json";
import superacaoAsset from "../assets/uma-historia-de-superacao.png.asset.json";
import despertarAsset from "../assets/o-despertar-para-o-mundo-literario.png.asset.json";
import "./DorinhaAuthorStoreProMax.css";
import "./DorinhaAuthorStoreProMaxV4.css";
import "./DorinhaCheckoutProMax.css";
import "./DorinhaTasteV2.css";
import "./DorinhaTripleSkill.css";
import "./DorinhaEditorialCompact.css";
import "./DorinhaAuthorStoreCompactV5.css";

type AssetMeta={url:string};
type ExternalStore={label:string;url:string};
type Book={id:string;slug:string;name:string;image_url:string|null;description:string|null;price:number;promotional_price:number|null;price_on_request:boolean;available:boolean;external_url?:string|null};
type MerchantProfile={id?:string|null;whatsapp?:string|null;author_name?:string|null;author_bio?:string|null;author_birthplace?:string|null;external_stores?:unknown;online_checkout_enabled?:boolean|null};
type Profile={merchant?:MerchantProfile|null;books?:unknown};
type Theme="light"|"dark";

const localBooks:Book[]=[
 {id:"imaginação",slug:"uma-viagem-ao-mundo-da-imaginacao",name:"Uma Viagem ao Mundo da Imaginação",image_url:(imagimacaoAsset as AssetMeta).url,description:"Uma obra para leitores que gostam de atravessar novas paisagens pela força da imaginação.",price:0,promotional_price:null,price_on_request:true,available:true},
 {id:"mente",slug:"mente-perversa",name:"Mente Perversa",image_url:(mentePerversaAsset as AssetMeta).url,description:"Uma leitura marcada por tensão, escolhas e camadas humanas que convidam à reflexão.",price:0,promotional_price:null,price_on_request:true,available:true},
 {id:"superação",slug:"uma-historia-de-superacao",name:"Uma História de Superação",image_url:(superacaoAsset as AssetMeta).url,description:"Uma narrativa sobre resistência, recomeços e a capacidade de seguir adiante.",price:0,promotional_price:null,price_on_request:true,available:true},
 {id:"despertar",slug:"o-despertar-para-o-mundo-literario",name:"O Despertar para o Mundo Literário",image_url:(despertarAsset as AssetMeta).url,description:"Um convite para descobrir a literatura como espaço de expressão, memória e transformação.",price:0,promotional_price:null,price_on_request:true,available:true}
];
const readTheme=():Theme=>{if(typeof window==="undefined")return"light";const saved=window.localStorage.getItem("precocerto-theme");if(saved==="dark"||saved==="light")return saved;return window.matchMedia?.("(prefers-color-scheme: dark)").matches?"dark":"light"};
const cleanPhone=(v:string)=>v.replace(/\D/g,"");
const wa=(phone:string,book?:string)=>`https://wa.me/${cleanPhone(phone)}?text=${encodeURIComponent(book?`Olá, Dorinha! Encontrei o livro “${book}” no PreçoCerto e gostaria de saber valor, disponibilidade e como comprar.`:"Olá, Dorinha! Encontrei sua página no PreçoCerto e gostaria de conhecer seus livros.")}`;
function asBookArray(value:unknown):Book[]{if(!Array.isArray(value))return[];return value.filter((item):item is Book=>Boolean(item&&typeof item==="object"&&typeof(item as Book).name==="string"&&typeof(item as Book).slug==="string"))}
function asStoreArray(value:unknown):ExternalStore[]{if(!Array.isArray(value))return[];return value.filter((item):item is ExternalStore=>Boolean(item&&typeof item==="object"&&typeof(item as ExternalStore).label==="string"&&typeof(item as ExternalStore).url==="string"&&Boolean((item as ExternalStore).url)))}

export function DorinhaAuthorStoreProMax(){
 const[profile,setProfile]=useState<Profile|null>(null);const[copied,setCopied]=useState(false);const[theme,setTheme]=useState<Theme>(readTheme);
 useEffect(()=>{document.documentElement.dataset.theme=theme;window.localStorage.setItem("precocerto-theme",theme)},[theme]);
 useEffect(()=>{document.title="Dorinha Barroso · Livros acreanos | PreçoCerto";let alive=true;(async()=>{if(!supabase)return;try{const{data,error}=await supabase.rpc("author_store_public_profile",{_slug:"dorinha-barroso-livros"});if(!alive||error||!data)return;const normalized=(typeof data==="string"?(()=>{try{return JSON.parse(data)}catch{return null}})():data)as Profile|null;if(normalized&&typeof normalized==="object")setProfile(normalized)}catch{return}})();return()=>{alive=false}},[]);
 const remoteBooks=useMemo(()=>asBookArray(profile?.books),[profile]);
 const books=useMemo(()=>{if(!remoteBooks.length)return localBooks;return localBooks.map(local=>{const match=remoteBooks.find(b=>b.slug===local.slug||b.name.toLowerCase()===local.name.toLowerCase());return match?{...local,...match,image_url:match.image_url||local.image_url}:local})},[remoteBooks]);
 const merchant=profile?.merchant&&typeof profile.merchant==="object"?profile.merchant:null;
 const author=merchant?.author_name||"Dorinha Barroso";const bio=merchant?.author_bio||"Uma autora acreana que transforma experiências, imaginação e sensibilidade em livros feitos para criar conexão com seus leitores.";const birthplace=merchant?.author_birthplace||"Acre";const whatsapp=merchant?.whatsapp||"5568999564762";const stores=useMemo(()=>asStoreArray(merchant?.external_stores).slice(0,3),[merchant]);
 const checkoutEnabled=Boolean(merchant?.id&&merchant?.online_checkout_enabled);const checkoutUrl=checkoutEnabled?`/loja/${encodeURIComponent(String(merchant?.id))}`:"";
 async function share(){const d={title:"Dorinha Barroso · Livros",text:"Conheça os livros de Dorinha Barroso no PreçoCerto.",url:window.location.href};if(navigator.share){try{await navigator.share(d);return}catch{setCopied(false)}}try{await navigator.clipboard?.writeText(window.location.href);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{setCopied(false)}}
 return <main className="dorinha-pro">
  <header className="dorinha-pro__top"><a href="/" className="dorinha-pro__brand">PreçoCerto <span>Literatura local</span></a><nav><a href="#livros">Livros</a><a href="#autora">A autora</a><button onClick={share} type="button"><Share2/>{copied?"Link copiado":"Compartilhar"}</button><button className="dorinha-pro__theme" onClick={()=>setTheme(t=>t==="dark"?"light":"dark")} type="button" aria-label={theme==="dark"?"Ativar modo claro":"Ativar modo escuro"}>{theme==="dark"?<Sun/>:<Moon/>}<span>{theme==="dark"?"Claro":"Escuro"}</span></button></nav></header>
  <section className="dorinha-pro__hero dorinha-pro__hero--v4"><div className="dorinha-pro__hero-bg" aria-hidden="true"/><div className="dorinha-pro__hero-copy"><span className="dorinha-pro__signature"><Feather/> Literatura acreana · espaço oficial</span><h1><em>Dorinha Barroso.</em><br/>Livros que guardam memória e imaginação.</h1><p>Conheça as quatro obras da escritora e compre diretamente neste espaço editorial.</p><div className="dorinha-pro__hero-actions"><a href="#livros">Conhecer os livros <ArrowRight/></a>{checkoutEnabled?<a href={checkoutUrl}><CreditCard/> Comprar diretamente</a>:<a href={wa(whatsapp)} target="_blank" rel="noreferrer"><MessageCircle/> Falar com a autora</a>}</div><div className="dorinha-pro__hero-meta"><span><CheckCircle2/> Página oficial</span>{checkoutEnabled&&<span><CreditCard/> Mercado Pago e Pix</span>}<span><MapPin/> {birthplace}</span></div></div><div className="dorinha-pro__hero-portrait"><img src="/dorinha-author-portrait-v2.webp" alt={`Retrato da escritora ${author}`}/><div><span>Escritora acreana</span><strong>{author}</strong></div></div></section>
  <section className="dorinha-pro__intro"><div><span className="dorinha-pro__section-note">Biblioteca da autora</span><h2>Quatro obras. Uma voz literária construída no Acre.</h2></div><p>Explore o acervo, conheça a trajetória de Dorinha e escolha a obra que mais conversa com o seu momento.</p></section>
  <section className="dorinha-pro__catalog" id="livros"><div className="dorinha-pro__section-head"><div><span className="dorinha-pro__section-note">Acervo</span><h2>Livros de Dorinha Barroso</h2></div><BookOpen/></div><div className="dorinha-pro__grid">{books.map((book,index)=>{const price=book.promotional_price||book.price;return <article className="dorinha-pro__book" key={book.id} style={{"--delay":`${index*45}ms`}as CSSProperties}><div className="dorinha-pro__cover"><span>{String(index+1).padStart(2,"0")}</span>{book.image_url?<img src={book.image_url} alt={`Capa de ${book.name}`} loading="lazy"/>:<BookOpen/>}</div><div className="dorinha-pro__book-body"><span className="dorinha-pro__book-label">{author}</span><h3>{book.name}</h3><p>{book.description||"Conheça esta obra e fale diretamente com a autora para receber mais informações."}</p><div className="dorinha-pro__book-footer"><strong>{book.price_on_request||!price?"Consulte o valor":price.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong><div className="dorinha-pro__book-actions">{checkoutEnabled?<a href={checkoutUrl}>Comprar <CreditCard/></a>:<a href={wa(whatsapp,book.name)} target="_blank" rel="noreferrer">Consultar <MessageCircle/></a>}</div></div></div></article>})}</div></section>
  <section className="dorinha-pro__author" id="autora"><figure className="dorinha-pro__author-photo"><img src="/dorinha-author-portrait-v2.webp" alt={`Foto da escritora ${author}`} loading="lazy"/><figcaption><strong>{author}</strong><span>Literatura feita no Acre</span></figcaption></figure><div className="dorinha-pro__author-copy"><span className="dorinha-pro__eyebrow"><Sparkles/> A escritora</span><h2>{author}</h2><p>{bio}</p><div className="dorinha-pro__facts"><div><strong>{books.length}</strong><span>obras publicadas aqui</span></div><div><strong>Acre</strong><span>origem literária</span></div><div><strong>Direto</strong><span>compra com a autora</span></div></div><a href={wa(whatsapp)} target="_blank" rel="noreferrer"><MessageCircle/> Conversar com Dorinha</a></div></section>
  {checkoutEnabled?<section className="dorinha-pro__pix"><div className="dorinha-pro__pix-icon"><QrCode/></div><div><span>Compra direta</span><h2>Escolha o livro. O pagamento acontece com segurança.</h2><p>Monte seu pedido e continue para o Mercado Pago. Na etapa de pagamento você pode escolher Pix ou outra forma disponível.</p></div><a href={checkoutUrl}>Ir para a compra <ArrowRight/></a></section>:<section className="dorinha-pro__pix"><div className="dorinha-pro__pix-icon"><MessageCircle/></div><div><span>Compra direta</span><h2>Fale com a autora</h2><p>O checkout online não está habilitado neste momento. Entre em contato para confirmar disponibilidade e formas de pagamento.</p></div><a href={wa(whatsapp)} target="_blank" rel="noreferrer">Falar com Dorinha <ArrowRight/></a></section>}
  <section className="dorinha-pro__market"><div><Store/><span>Outros canais</span><h2>Encontre Dorinha também em outras plataformas.</h2><p>{stores.length?"Se preferir, acesse uma das plataformas cadastradas abaixo.":"A compra principal acontece diretamente pelo espaço da autora no PreçoCerto."}</p></div><div className="dorinha-pro__market-actions">{stores.map(store=><a key={`${store.label}-${store.url}`} href={store.url} target="_blank" rel="noreferrer">{store.label}<ExternalLink/></a>)}</div></section>
  <footer className="dorinha-pro__footer"><div><strong>Dorinha Barroso</strong><span>Escritora acreana · espaço oficial no PreçoCerto</span></div><a href="/estabelecimentos">Conhecer o PreçoCerto <ArrowRight/></a></footer>
 </main>
}
