import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { BadgeCheck, ChevronRight, Music2, Sparkles } from "lucide-react";
import { useLocation } from "react-router-dom";
import { supabase } from "../lib/supabase";

type Item={display_name:string;slug:string;tagline:string|null;youtube_url:string|null;verified:boolean;accent_color:string|null};
export function LocalCultureSpotlight(){
 const location=useLocation();const[host,setHost]=useState<HTMLElement|null>(null),[items,setItems]=useState<Item[]>([]);
 useEffect(()=>{if(location.pathname!=="/"){setHost(null);return}let own:HTMLElement|null=null;const mount=()=>{const main=document.querySelector("main");if(!main)return false;const old=document.getElementById("pc-local-culture");if(old){setHost(old);return true}own=document.createElement("div");own.id="pc-local-culture";const premium=document.getElementById("pc-premium-home");if(premium)premium.after(own);else main.appendChild(own);setHost(own);return true};if(!mount()){const mo=new MutationObserver(()=>{if(mount())mo.disconnect()});mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()}return()=>own?.remove()},[location.pathname]);
 useEffect(()=>{if(location.pathname!=="/"||!supabase)return;void(async()=>{const{data}=await supabase.from("cultural_profiles").select("display_name,slug,tagline,youtube_url,verified,accent_color").eq("featured",true).limit(4);setItems((data??[]) as Item[])})()},[location.pathname]);
 if(!host||!items.length)return null;
 return createPortal(<section style={s.wrap}><div style={s.shell}><div style={s.copy}><div style={s.art}><svg viewBox="0 0 72 72"><path d="M24 51V20l30-6v31"/><circle cx="17" cy="53" r="8"/><circle cx="47" cy="47" r="8"/><path d="M24 29l30-6"/></svg></div><div><span style={s.kicker}><Sparkles size={12}/> CRIADORES LOCAIS</span><h2 style={s.h2}>Talento da cidade, em uma vitrine discreta.</h2><p style={s.text}>Projetos verificados para conhecer em poucos cliques.</p></div></div><div style={s.grid}>{items.map(x=><a key={x.slug} href={`/cultura/${x.slug}`} style={{...s.card,borderColor:x.accent_color?`${x.accent_color}55`:undefined}}><div style={{...s.icon,background:x.accent_color||"var(--pc-color-primary)"}}><Music2 size={17}/></div><span style={s.name}><b>{x.display_name}</b><small>{x.tagline||"Projeto cultural local"}</small></span>{x.verified&&<BadgeCheck size={14}/>}<ChevronRight size={15}/></a>)}</div><div style={s.footer}><span>Você cria em Feijó?</span><a href="/fale-conosco">Apresente seu projeto <ChevronRight size={14}/></a></div></div></section>,host);
}
const s:Record<string,React.CSSProperties>={wrap:{maxWidth:1240,margin:"0 auto",padding:"10px 24px 28px",fontFamily:"'Manrope Variable', Manrope, system-ui, sans-serif"},shell:{borderRadius:18,padding:16,background:"linear-gradient(125deg,var(--pc-color-foreground),var(--pc-color-foreground))",color:"white",boxShadow:"0 12px 34px rgba(45,23,57,.1)"},copy:{display:"flex",alignItems:"center",gap:14},art:{width:72,height:72,borderRadius:14,background:"rgba(255,255,255,.07)",display:"grid",placeItems:"center",flex:"0 0 auto"},kicker:{display:"inline-flex",gap:5,alignItems:"center",fontSize:8.5,fontWeight:950,letterSpacing:".14em",color:"color-mix(in srgb, var(--pc-color-primary) 9%, var(--pc-color-surface))"},h2:{fontFamily:"Georgia,serif",fontSize:"clamp(1.25rem,2.2vw,1.75rem)",lineHeight:1.05,letterSpacing:"-.035em",margin:"5px 0"},text:{color:"var(--pc-color-muted)",fontSize:11,margin:0},grid:{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:7,marginTop:12},card:{minHeight:58,border:"1px solid rgba(255,255,255,.12)",borderRadius:12,padding:8,background:"rgba(255,255,255,.05)",display:"grid",gridTemplateColumns:"38px 1fr auto auto",alignItems:"center",gap:8,color:"white",textDecoration:"none"},icon:{width:38,height:38,borderRadius:10,display:"grid",placeItems:"center",color:"white"},name:{display:"grid",minWidth:0},footer:{display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",marginTop:10,paddingTop:10,borderTop:"1px solid rgba(255,255,255,.09)",fontSize:10,color:"var(--pc-color-muted)"}};
