import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Check, Link2, ShieldCheck, Store } from "lucide-react";
import { supabase } from "../lib/roles";

type Plan={code:string;name:string;monthly_price:number;commission_rate:number;features:Record<string,unknown>};
type Establishment={id:string;name:string;neighborhood:string|null;kind:string|null};
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});

export function MerchantOnboardingPage(){
 const [plans,setPlans]=useState<Plan[]>([]),[establishments,setEstablishments]=useState<Establishment[]>([]),[plan,setPlan]=useState("professional"),[user,setUser]=useState<any>(null),[state,setState]=useState<"idle"|"sending"|"ok"|"error">("idle"),[message,setMessage]=useState("");
 useEffect(()=>{void(async()=>{if(!supabase)return;const [{data:s},{data:p},{data:e}]=await Promise.all([supabase.auth.getSession(),supabase.from("platform_plans").select("code,name,monthly_price,commission_rate,features").eq("active",true).order("commission_rate",{ascending:false}),supabase.from("establishments").select("id,name,neighborhood,kind").order("name")]);setUser(s.session?.user??null);setPlans((p??[]) as Plan[]);setEstablishments((e??[]) as Establishment[])})()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!user){setState("error");setMessage("Entre na sua conta do Preço Certo antes de enviar o cadastro. Assim o estabelecimento será vinculado ao seu painel.");return}setState("sending");const fd=new FormData(e.currentTarget),business_name=String(fd.get("business_name")||"").trim(),neighborhood=String(fd.get("neighborhood")||"").trim(),owner_name=String(fd.get("owner_name")||"").trim(),phone=String(fd.get("phone")||"").trim(),email=String(fd.get("email")||user.email||"").trim(),kind=String(fd.get("kind")||"market"),establishment_id=String(fd.get("establishment_id")||"").trim()||null;if(!business_name||!neighborhood){setState("error");setMessage("Informe o nome do comércio e o bairro.");return}const {error}=await supabase.from("merchant_applications").insert({applicant_user_id:user.id,business_name,neighborhood,kind,owner_name:owner_name||null,phone:phone||null,email:email||null,desired_plan:plan,establishment_id,status:"pending"});if(error){setState("error");setMessage(error.message);return}setState("ok");setMessage(establishment_id?"Solicitação enviada. Após a validação, o catálogo público desse estabelecimento será importado para o seu painel para você revisar estoque e disponibilidade.":"Solicitação enviada. Quando a administração aprovar, seu painel de comerciante será liberado automaticamente.")}
  return <main style={s.page}><header style={s.top}><a href="/" style={s.back}><ArrowLeft size={16}/> Voltar</a><strong>PreçoCerto · Para comerciantes</strong></header><section style={s.hero}><div><span style={s.kicker}>COMÉRCIO LOCAL, OPERAÇÃO DIGITAL</span><h1 style={s.h1}>Escolha seu plano e prepare sua loja para vender.</h1><p style={s.lead}>Após a aprovação, você terá catálogo, pedidos ao vivo, financeiro, entrega, equipe e integração de pagamentos em um painel separado da administração da plataforma.</p></div><div style={s.security}><ShieldCheck/><div><strong>Seu painel é privado</strong><p>A administração acompanha cadastro, plano e indicadores agregados, mas não opera preços, estoque, pedidos ou caixa da sua loja.</p></div></div></section>
  <section style={s.plans}>{plans.map(p=><button type="button" key={p.code} onClick={()=>setPlan(p.code)} style={{...s.plan,...(plan===p.code?s.planOn:{})}}><span style={s.kicker}>{p.code.toUpperCase()}</span><h2>{p.name}</h2><strong style={s.price}>{p.monthly_price>0?`${money.format(p.monthly_price)}/mês`:"Valor definido pela plataforma"}</strong><small>Comissão configurada: {Number(p.commission_rate).toLocaleString("pt-BR")}%</small><div style={s.checks}><span><Check size={14}/> Catálogo e pedidos</span>{!!p.features?.finance&&<span><Check size={14}/> Financeiro</span>}{!!p.features?.delivery&&<span><Check size={14}/> Entregas</span>}{!!p.features?.team&&<span><Check size={14}/> Equipe</span>}</div></button>)}</section>
  <section style={s.formCard}><div><Store size={28}/><h2>Dados do estabelecimento</h2><p>Use a mesma conta com a qual você administrará o comércio.</p><div style={s.bridge}><Link2 size={18}/><span>Se a sua loja já aparece na comparação de preços, selecione-a no formulário. Isso evita duplicidade e prepara a importação do catálogo já existente.</span></div>{!user&&<div style={s.warn}>Você ainda não está autenticado. Entre pela página inicial antes de enviar.</div>}</div><form onSubmit={submit} style={s.form}><label>Minha loja já aparece no Preço Certo<select name="establishment_id" defaultValue=""><option value="">Não / não encontrei</option>{establishments.map(est=><option key={est.id} value={est.id}>{est.name}{est.neighborhood?` · ${est.neighborhood}`:""}</option>)}</select></label><label>Nome do comércio<input name="business_name" required placeholder="Ex.: Mercado Avenida"/></label><div style={s.two}><label>Bairro<input name="neighborhood" required placeholder="Centro"/></label><label>Segmento<select name="kind"><option value="market">Mercado / supermercado</option><option value="butcher">Açougue</option><option value="pharmacy">Farmácia</option><option value="other">Outro</option></select></label></div><div style={s.two}><label>Responsável<input name="owner_name" placeholder="Nome do responsável"/></label><label>WhatsApp<input name="phone" inputMode="tel" placeholder="(68) 99999-9999"/></label></div><label>E-mail<input name="email" type="email" defaultValue={user?.email||""}/></label><div style={s.selected}>Plano selecionado: <strong>{plans.find(p=>p.code===plan)?.name||plan}</strong></div>{message&&<div style={state==="ok"?s.ok:s.warn}>{message}</div>}<button disabled={state==="sending"||!user} style={s.submit}>{state==="sending"?"Enviando…":"Enviar para aprovação"}</button></form></section></main>;
}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"var(--pc-color-background)",color:"var(--pc-color-foreground)",fontFamily:"Manrope Variable", Manrope, system-ui, sans-serif",paddingBottom:70},top:{height:64,padding:"0 clamp(18px,4vw,60px)",display:"flex",alignItems:"center",justifyContent:"space-between",background:"white",borderBottom:"1px solid var(--pc-color-border)"},back:{display:"flex",alignItems:"center",gap:6,color:"inherit",textDecoration:"none",fontWeight:700},hero:{maxWidth:1180,margin:"0 auto",padding:"58px 20px 30px",display:"grid",gridTemplateColumns:"1.25fr .75fr",gap:24,alignItems:"end"},kicker:{fontSize:10,fontWeight:900,letterSpacing:".13em",opacity:.58},h1:{fontSize:"clamp(36px,5vw,62px)",lineHeight:1,letterSpacing:"-.055em",margin:"10px 0 18px"},lead:{fontSize:16,color:"var(--pc-color-muted)",lineHeight:1.65,maxWidth:720},security:{background:"var(--pc-color-background)",border:"1px solid var(--pc-color-muted)",borderRadius:18,padding:20,display:"flex",gap:12},plans:{maxWidth:1180,margin:"0 auto",padding:"10px 20px 24px",display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12},plan:{textAlign:"left",padding:22,borderRadius:17,border:"1px solid var(--pc-color-border)",background:"white",cursor:"pointer",display:"grid",gap:7},planOn:{border:"2px solid var(--pc-color-primary)",boxShadow:"0 12px 34px rgba(31,91,59,.12)"},price:{fontSize:18},checks:{display:"grid",gap:5,marginTop:10,fontSize:12,color:"var(--pc-color-muted)"},formCard:{maxWidth:1140,margin:"0 auto",background:"white",border:"1px solid var(--pc-color-border)",borderRadius:20,padding:26,display:"grid",gridTemplateColumns:".7fr 1.3fr",gap:30},form:{display:"grid",gap:12},two:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10},selected:{padding:12,borderRadius:10,background:"var(--pc-color-background)"},bridge:{marginTop:18,padding:13,borderRadius:12,background:"var(--pc-color-background)",display:"flex",gap:9,fontSize:13,lineHeight:1.45},submit:{minHeight:48,border:0,borderRadius:11,background:"var(--pc-color-foreground)",color:"white",fontWeight:850,cursor:"pointer"},warn:{padding:12,borderRadius:10,background:"var(--pc-color-background)",color:"var(--pc-color-accent)",fontSize:13},ok:{padding:12,borderRadius:10,background:"var(--pc-color-background)",color:"var(--pc-color-primary)",fontSize:13}}
