import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgeCheck, Building2, MapPin, Search, ShoppingBag, Store, Tag, Truck } from "lucide-react";
import { useParams } from "react-router-dom";
import { supabase } from "../lib/roles";
import { getStoreLogoUrl } from "../data/storeLogos";
import "./PublicEstablishmentCatalog.css";

type Item={id:string;name:string;image_url?:string|null;category?:string|null;brand?:string|null;size?:string|null;unit?:string|null;price:number;previous_price?:number|null;promotional_price?:number|null;available:boolean;source:string;updated_at?:string|null};
type Profile={establishment:{id:string;slug:string|null;name:string;neighborhood:string|null;kind:string|null;brand_color:string|null;logo_url:string|null;short_description:string|null;is_verified:boolean;is_sponsored:boolean;partner_tier:string};merchant:null|{id:string;business_type:string;online_sales_enabled:boolean;delivery_enabled:boolean;pickup_enabled:boolean;phone:string|null;address:any;service_settings:any};catalog:Item[]};
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});

export function PublicEstablishmentCatalog(){
 const {identifier=""}=useParams();
 const [profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[category,setCategory]=useState("all");
 useEffect(()=>{void(async()=>{if(!supabase){setLoading(false);return}const {data}=await supabase.rpc("establishment_public_catalog",{_identifier:identifier});setProfile((data||null) as Profile|null);setLoading(false)})()},[identifier]);
 const categories=useMemo(()=>Array.from(new Set((profile?.catalog||[]).map(x=>x.category).filter(Boolean) as string[])).sort(),[profile]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return (profile?.catalog||[]).filter(x=>(!q||`${x.name} ${x.brand||""} ${x.category||""}`.toLowerCase().includes(q))&&(category==="all"||x.category===category))},[profile,query,category]);
 if(loading)return <main className="storefront"><div className="sf-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center"}}>Carregando catálogo…</div></main>;
 if(!profile)return <main className="storefront"><div className="sf-shell" style={{minHeight:"100vh",display:"grid",placeItems:"center",textAlign:"center"}}><div><Store size={42}/><h1>Estabelecimento não encontrado</h1><a href="/estabelecimentos">Voltar aos estabelecimentos</a></div></div></main>;
 const e=profile.establishment,m=profile.merchant,online=Boolean(m?.online_sales_enabled),direct=Boolean(m?.service_settings?.direct_sales_enabled),author=m?.business_type==="books_author"||e.slug==="dorinha-barroso-livros";
 const logo=e.logo_url||getStoreLogoUrl(e.name);
 return <main className="storefront" style={{"--sf-brand":e.brand_color||"var(--pc-color-primary)"} as React.CSSProperties}>
   <header className="sf-header"><div className="sf-shell sf-header__inner"><a className="sf-back" href="/estabelecimentos"><ArrowLeft size={16}/> Estabelecimentos</a><a className="sf-home" href="/" aria-label="PreçoCerto - início"><img src="/logo-preco-certo-inversa.svg" alt="PreçoCerto"/></a></div></header>
   <section className="sf-hero"><div className="sf-hero__image"/><div className="sf-hero__overlay"/><div className="sf-shell sf-hero__inner"><div className="sf-identity"><div className="sf-logo" style={{background:e.brand_color||"var(--pc-color-foreground)"}}>{logo?<img src={logo} alt={`Logomarca ${e.name}`}/>:<Store aria-hidden="true"/>}</div><div><div className="sf-badges">{e.is_verified&&<span className="sf-badge"><BadgeCheck size={13}/> Verificado</span>}{e.is_sponsored&&<span className="sf-badge"><Tag size={13}/> Patrocinado</span>}{online&&<span className="sf-badge"><ShoppingBag size={13}/> Compra online</span>}{direct&&<span className="sf-badge"><ShoppingBag size={13}/> Venda direta</span>}</div><h1>{e.name}</h1><p>{e.short_description||"Explore os produtos e preços deste estabelecimento no PreçoCerto."}</p><div className="sf-meta">{e.neighborhood&&<span><MapPin size={14}/>{e.neighborhood}</span>}{m?.delivery_enabled&&<span><Truck size={14}/>Entrega</span>}{m?.pickup_enabled&&<span><Building2 size={14}/>Retirada</span>}</div></div></div><aside className="sf-summary"><strong>{profile.catalog.length}</strong><span>itens disponíveis no catálogo</span>{author?<a href="/autora/dorinha-barroso">Abrir espaço da autora</a>:online&&m?<a href={`/loja/${m.id}`}><ShoppingBag size={15}/> Comprar online</a>:direct?<div className="sf-summary-note">Venda direta disponível</div>:<div className="sf-summary-note">Consulte e compare preços</div>}</aside></div></section>
   <section className="sf-content"><div className="sf-shell"><div className="sf-heading"><div><span>Catálogo local</span><h2>Encontre o que precisa nesta loja.</h2><p>Pesquise produtos, filtre por categoria e confira os preços disponíveis antes de sair de casa.</p></div>{online&&m&&<a href={`/loja/${m.id}`}><ShoppingBag size={16}/> Ir para compra online</a>}</div><div className="sf-toolbar"><label className="sf-search"><Search size={18}/><input value={query} onChange={ev=>setQuery(ev.target.value)} placeholder="Buscar produto, marca ou categoria" aria-label={`Buscar no catálogo de ${e.name}`}/></label><select value={category} onChange={ev=>setCategory(ev.target.value)} aria-label="Filtrar categoria"><option value="all">Todas as categorias</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="sf-grid">{filtered.map(item=>{const price=item.promotional_price??item.price;return <article className="sf-card" key={item.id}><div className="sf-media">{item.image_url?<img src={item.image_url} alt={item.name} loading="lazy"/>:<ShoppingBag size={28}/>}</div><div className="sf-body">{item.category&&<span className="sf-type">{item.category}</span>}<h3>{item.name}</h3>{(item.brand||item.size||item.unit)&&<small>{[item.brand,item.size,item.unit].filter(Boolean).join(" · ")}</small>}<div className="sf-price">{brl.format(Number(price||0))}</div>{(item.promotional_price!=null||item.previous_price!=null)&&<small className="sf-old">{brl.format(Number(item.promotional_price!=null?item.price:item.previous_price||0))}</small>}<small className="sf-source">{item.source==="merchant"?"Catálogo do estabelecimento":"Preço monitorado pelo PreçoCerto"}</small></div></article>})}{!filtered.length&&<div className="sf-empty">Nenhum item encontrado com esses filtros.</div>}</div></div></section>
   <footer className="sf-footer"><div className="sf-shell sf-footer__inner"><span>{e.name} · Feijó-AC</span><a href="/estabelecimentos">Ver outros estabelecimentos</a></div></footer>
 </main>;
}
