-- Operational admin control center. Applied to production Supabase on 2026-08-17.

create or replace function public.admin_control_center_snapshot()
returns jsonb language plpgsql stable security definer set search_path=''
as $$
declare result jsonb; begin
  if (select auth.uid()) is null or not private.is_platform_admin() then raise exception 'Acesso administrativo negado' using errcode='42501'; end if;
  select jsonb_build_object(
    'summary',jsonb_build_object('merchants',(select count(*) from public.merchants),'activeMerchants',(select count(*) from public.merchants where status='active'),'pendingApplications',(select count(*) from public.merchant_applications where status='pending'),'orders',(select count(*) from public.orders),'ordersToday',(select count(*) from public.orders where created_at>=date_trunc('day',now())),'users',(select count(*) from public.profiles),'prices',(select count(*) from public.prices),'pricesToday',(select count(*) from public.prices where captured_at>=date_trunc('day',now())),'auditEntries',(select count(*) from public.platform_audit_log),'gmvToday',(select coalesce(sum(total),0) from public.orders where created_at>=date_trunc('day',now()) and status<>'cancelled'),'platformRevenueToday',(select coalesce(sum(platform_fee),0) from public.orders where created_at>=date_trunc('day',now()) and status<>'cancelled')),
    'applications',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (select id,business_name,owner_name,email,phone,neighborhood,business_type,kind,desired_plan,status,created_at,reviewed_at,rejection_reason,merchant_id from public.merchant_applications order by created_at desc limit 60)x),'[]'::jsonb),
    'merchants',coalesce((select jsonb_agg(to_jsonb(x) order by x.name) from (select m.id,m.name,m.business_type,m.status,m.plan_code,m.online_sales_enabled,m.delivery_enabled,m.pickup_enabled,m.email,m.phone,m.created_at,m.updated_at,(select count(*) from public.merchant_products mp where mp.merchant_id=m.id and mp.active=true) product_count,(select count(*) from public.orders o where o.merchant_id=m.id) order_count,(select count(*) from public.merchant_members mm where mm.merchant_id=m.id and mm.active=true) member_count from public.merchants m order by m.name limit 100)x),'[]'::jsonb),
    'orders',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (select o.id,o.order_number,o.status,o.payment_status,o.total,o.platform_fee,o.delivery_type,o.customer_name,o.created_at,o.updated_at,m.name merchant_name from public.orders o join public.merchants m on m.id=o.merchant_id order by o.created_at desc limit 100)x),'[]'::jsonb),
    'users',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (select p.id,p.display_name,p.role profile_role,p.created_at,p.updated_at,u.email,u.email_confirmed_at,u.last_sign_in_at,coalesce((select jsonb_agg(ur.role::text order by ur.role::text) from public.user_roles ur where ur.user_id=p.id),'[]'::jsonb) roles from public.profiles p left join auth.users u on u.id=p.id order by p.created_at desc limit 120)x),'[]'::jsonb),
    'prices',coalesce((select jsonb_agg(to_jsonb(x) order by x.captured_at desc) from (select pr.id,pr.value,pr.previous_value,pr.captured_at,p.name product_name,p.category,e.name establishment_name,e.neighborhood,case when pr.previous_value is null or pr.previous_value=0 then null else round(((pr.value-pr.previous_value)/pr.previous_value)*100,2) end variation_percent from public.prices pr join public.products p on p.id=pr.product_id join public.establishments e on e.id=pr.establishment_id order by pr.captured_at desc limit 120)x),'[]'::jsonb),
    'priceMap',coalesce((select jsonb_agg(to_jsonb(x) order by x.price_count desc) from (select e.id,e.name,e.neighborhood,count(pr.id) price_count,round(avg(pr.value),2) average_price,min(pr.value) min_price,max(pr.value) max_price,max(pr.captured_at) last_capture from public.establishments e left join public.prices pr on pr.establishment_id=e.id group by e.id,e.name,e.neighborhood having count(pr.id)>0 order by count(pr.id) desc limit 40)x),'[]'::jsonb),
    'audit',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (select l.id,l.action,l.entity_type,l.entity_id,l.metadata,l.created_at,p.display_name actor_name,u.email actor_email,m.name merchant_name from public.platform_audit_log l left join public.profiles p on p.id=l.user_id left join auth.users u on u.id=l.user_id left join public.merchants m on m.id=l.merchant_id order by l.created_at desc limit 100)x),'[]'::jsonb),
    'activity',coalesce((select jsonb_agg(to_jsonb(x) order by x.events desc) from (select ua.action,ua.entity_type,count(*) events,max(ua.created_at) last_event from public.user_actions ua group by ua.action,ua.entity_type order by count(*) desc limit 40)x),'[]'::jsonb)
  ) into result; return result; end; $$;
revoke all on function public.admin_control_center_snapshot() from public; grant execute on function public.admin_control_center_snapshot() to authenticated;

create or replace function public.admin_update_merchant(_merchant_id uuid,_status text default null,_online_sales_enabled boolean default null)
returns jsonb language plpgsql security definer set search_path=''
as $$declare before_row jsonb;after_row jsonb;begin if (select auth.uid()) is null or not private.is_platform_admin() then raise exception 'Acesso administrativo negado' using errcode='42501';end if;if _status is not null and _status not in ('active','inactive','suspended') then raise exception 'Status inválido';end if;select to_jsonb(m) into before_row from public.merchants m where id=_merchant_id;if before_row is null then raise exception 'Comerciante não encontrado';end if;update public.merchants set status=coalesce(_status,status),online_sales_enabled=coalesce(_online_sales_enabled,online_sales_enabled),online_sales_started_at=case when coalesce(_online_sales_enabled,online_sales_enabled)=true and online_sales_started_at is null then now() else online_sales_started_at end,updated_at=now() where id=_merchant_id;select to_jsonb(m) into after_row from public.merchants m where id=_merchant_id;insert into public.platform_audit_log(merchant_id,user_id,action,entity_type,entity_id,before_data,after_data) values(_merchant_id,(select auth.uid()),'admin_update_merchant','merchant',_merchant_id::text,before_row,after_row);return after_row;end;$$;
revoke all on function public.admin_update_merchant(uuid,text,boolean) from public; grant execute on function public.admin_update_merchant(uuid,text,boolean) to authenticated;

create or replace function public.admin_set_user_role(_user_id uuid,_role public.app_role,_enabled boolean default true)
returns jsonb language plpgsql security definer set search_path=''
as $$declare caller uuid:=(select auth.uid());is_super boolean;roles_json jsonb;begin select exists(select 1 from public.user_roles where user_id=caller and role='super_admin'::public.app_role) into is_super;if caller is null or not is_super then raise exception 'Somente superadministrador pode alterar papéis' using errcode='42501';end if;if _user_id=caller and _role='super_admin'::public.app_role and _enabled=false then raise exception 'Não é permitido remover seu próprio acesso de superadministrador';end if;if _enabled then insert into public.user_roles(user_id,role) values(_user_id,_role) on conflict(user_id,role) do nothing;else delete from public.user_roles where user_id=_user_id and role=_role;end if;if _role in ('super_admin'::public.app_role,'admin'::public.app_role,'moderator'::public.app_role) then update public.profiles set role=case when _enabled then 'admin' else role end,updated_at=now() where id=_user_id;end if;select coalesce(jsonb_agg(role::text order by role::text),'[]'::jsonb) into roles_json from public.user_roles where user_id=_user_id;insert into public.platform_audit_log(user_id,action,entity_type,entity_id,metadata) values(caller,case when _enabled then 'admin_grant_role' else 'admin_revoke_role' end,'user',_user_id::text,jsonb_build_object('role',_role::text));return jsonb_build_object('user_id',_user_id,'roles',roles_json);end;$$;
revoke all on function public.admin_set_user_role(uuid,public.app_role,boolean) from public; grant execute on function public.admin_set_user_role(uuid,public.app_role,boolean) to authenticated;

create or replace function public.admin_cancel_order(_order_id uuid,_reason text default 'Cancelado pela administração')
returns jsonb language plpgsql security definer set search_path=''
as $$declare before_row jsonb;after_row jsonb;merchant uuid;begin if (select auth.uid()) is null or not private.is_platform_admin() then raise exception 'Acesso administrativo negado' using errcode='42501';end if;select to_jsonb(o),o.merchant_id into before_row,merchant from public.orders o where id=_order_id;if before_row is null then raise exception 'Pedido não encontrado';end if;update public.orders set status='cancelled',cancellation_reason=coalesce(nullif(trim(_reason),''),'Cancelado pela administração'),cancelled_at=coalesce(cancelled_at,now()),updated_at=now() where id=_order_id and status<>'delivered';select to_jsonb(o) into after_row from public.orders o where id=_order_id;insert into public.platform_audit_log(merchant_id,user_id,action,entity_type,entity_id,before_data,after_data,metadata) values(merchant,(select auth.uid()),'admin_cancel_order','order',_order_id::text,before_row,after_row,jsonb_build_object('reason',_reason));return after_row;end;$$;
revoke all on function public.admin_cancel_order(uuid,text) from public; grant execute on function public.admin_cancel_order(uuid,text) to authenticated;

-- Keep the broad profile role compatible with profiles_role_check; detailed merchant authority lives in user_roles.
create or replace function public.review_merchant_application(_application_id uuid,_decision text,_admin_notes text default null)
returns jsonb language plpgsql security definer set search_path=''
as $$declare _app public.merchant_applications%rowtype;_merchant_id uuid;begin if (select auth.uid()) is null or not private.is_platform_admin() then raise exception 'Acesso negado' using errcode='42501';end if;if _decision not in ('approved','rejected') then raise exception 'Decisão inválida';end if;select * into _app from public.merchant_applications where id=_application_id for update;if not found then raise exception 'Solicitação não encontrada';end if;if _app.status<>'pending' then raise exception 'Solicitação já revisada';end if;if _decision='approved' then insert into public.merchants(name,legal_name,document,phone,email,address,status,plan_code,delivery_enabled,pickup_enabled,establishment_id,business_type,online_sales_enabled,online_sales_message) values(_app.business_name,_app.legal_name,_app.document_number,_app.phone,_app.email,case when _app.address='{}'::jsonb then jsonb_build_object('neighborhood',_app.neighborhood) else _app.address end,'active',_app.desired_plan,false,true,_app.establishment_id,coalesce(nullif(_app.business_type,''),nullif(_app.kind,''),'grocery'),false,'Loja aprovada. Ative vendas online no painel quando estiver pronta.') returning id into _merchant_id;if _app.applicant_user_id is not null then insert into public.merchant_members(merchant_id,user_id,role,active) values(_merchant_id,_app.applicant_user_id,'owner',true) on conflict(merchant_id,user_id) do update set role='owner',active=true;insert into public.user_roles(user_id,role) values(_app.applicant_user_id,'merchant_owner'::public.app_role) on conflict(user_id,role) do nothing;update public.profiles set role='merchant',updated_at=now() where id=_app.applicant_user_id;end if;if _app.establishment_id is not null then perform public.import_establishment_catalog_to_merchant(_merchant_id);end if;end if;update public.merchant_applications set status=_decision,admin_notes=_admin_notes,rejection_reason=case when _decision='rejected' then _admin_notes else null end,reviewed_by=(select auth.uid()),reviewed_at=now(),merchant_id=_merchant_id,updated_at=now() where id=_application_id;insert into public.platform_audit_log(merchant_id,user_id,action,entity_type,entity_id,metadata) values(_merchant_id,(select auth.uid()),'merchant_application_'||_decision,'merchant_application',_application_id::text,jsonb_build_object('business_name',_app.business_name,'establishment_id',_app.establishment_id));return jsonb_build_object('status',_decision,'merchant_id',_merchant_id);end;$$;
