create or replace function public.admin_catalog_snapshot()
returns jsonb language plpgsql stable security definer set search_path=''
as $$
declare result jsonb;
begin
  if (select auth.uid()) is null or not private.is_platform_admin() then raise exception 'Acesso negado' using errcode='42501'; end if;
  select jsonb_build_object(
    'products',coalesce((select jsonb_agg(x order by lower(x->>'name')) from (select jsonb_build_object('id',p.id,'name',p.name,'brand',p.brand,'category',p.category,'size',p.size,'unit',p.unit,'barcode',p.barcode,'slug',p.slug,'image_url',p.image_url,'created_at',p.created_at,'store_count',(select count(distinct pr.establishment_id) from public.prices pr where pr.product_id=p.id),'latest_price',(select pr.value from public.prices pr where pr.product_id=p.id order by pr.captured_at desc nulls last limit 1),'latest_update',(select max(pr.captured_at) from public.prices pr where pr.product_id=p.id)) x from public.products p) q),'[]'::jsonb),
    'establishments',coalesce((select jsonb_agg(x order by lower(x->>'name')) from (select jsonb_build_object('id',e.id,'name',e.name,'neighborhood',e.neighborhood,'kind',e.kind,'slug',e.slug,'is_verified',e.is_verified,'is_demo',e.is_demo,'logo_url',e.logo_url,'short_description',e.short_description,'address',e.address,'latitude',e.latitude,'longitude',e.longitude,'created_at',e.created_at,'product_count',(select count(distinct pr.product_id) from public.prices pr where pr.establishment_id=e.id),'last_price_update',(select max(pr.captured_at) from public.prices pr where pr.establishment_id=e.id),'merchant_id',(select m.id from public.merchants m where m.establishment_id=e.id limit 1),'merchant_is_demo',(select m.is_demo from public.merchants m where m.establishment_id=e.id limit 1)) x from public.establishments e) q),'[]'::jsonb),
    'coverageGaps',coalesce((with presence as (select distinct product_id,establishment_id from public.prices),popularity as (select product_id,count(*) store_count from presence group by product_id),candidates as (select e.id establishment_id,e.name establishment_name,p.id product_id,p.name product_name,p.category,p.brand,pop.store_count,(select min(pr.value) from public.prices pr where pr.product_id=p.id) reference_price from public.establishments e cross join public.products p join popularity pop on pop.product_id=p.id and pop.store_count>0 where not exists(select 1 from presence x where x.establishment_id=e.id and x.product_id=p.id)) select jsonb_agg(jsonb_build_object('establishment_id',establishment_id,'establishment_name',establishment_name,'product_id',product_id,'product_name',product_name,'category',category,'brand',brand,'stores_with_product',store_count,'reference_price',reference_price) order by store_count desc,lower(product_name),lower(establishment_name)) from (select * from candidates order by store_count desc,product_name limit 1500) g),'[]'::jsonb)
  ) into result;
  return result;
end;$$;
